ingress:
  host: "eu.scopa.local"

redis:
  host: "eu-scopa-redis.cache-eu.svc.cluster.local"

env:
  REDIS_SENTINEL_HOST: "eu-scopa-redis.cache-eu.svc.cluster.local"

soketi:
  host: "scopa-eu-soketi-service"

db:
  localNode: "yb-tserver-0.yb-tservers.db.svc.cluster.local"
  backups: "yb-tserver-1.yb-tservers.db.svc.cluster.local,yb-tserver-2.yb-tservers.db.svc.cluster.local"
