replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

image:
  repository: scopa2
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP

ingress:
  host: "scopa.local"

db:
  port: "5433"
  database: "yugabyte"

redis:
  host: "scopa-redis"
  port: "6379"
  password: ""

soketi:
  replicaCount: 2
  host: "scopa-soketi-service"
  port: "6001"
  appId: "app-id"
  appKey: "app-key"
  appSecret: "app-secret"

# Global Env Vars (overrides .env for K8s distributed deployment)
env:
  OCTANE_HTTPS: "true"
  DB_CONNECTION: "pgsql"
  REDIS_CLIENT: "phpredis-sentinel"
  CACHE_STORE: "redis"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  LOG_CHANNEL: "stderr"
  APP_MAINTENANCE_DRIVER: "cache"
  APP_MAINTENANCE_STORE: "redis"
  REDIS_SENTINEL_SERVICE: "mymaster"
  REDIS_SENTINEL_PORT: "26379"
  # --- APP KEY: Must be shared across all pods ---
  APP_KEY: "base64:fulavu5hC7LK1C7CDieOVN36wPRGQfKgh1fgyLPIyVM="

